//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLearningApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public System.DateTime Date { get; set; }
        public int Id_User { get; set; }
        public byte[] Avatar { get; set; }
        public string AvatarMimeType { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Id_Address { get; set; }
        public bool CanLoad { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual User User { get; set; }
    }
}
